
import javax.swing.event.SwingPropertyChangeSupport;

// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {

		int number = Integer.parseInt(args[0]); //100
		int counterLessOrEqual = 0;
		int counterMore = 0;

		for (int i = 0; i < number ; i++){

			Double randomNum = Math.random();

			if (randomNum <= 0.5){
				counterLessOrEqual += 1;
			}
			 else{
				counterMore += 1;
			 }

		}

		System.out.println("> 0.5: " + counterMore + " times");
		System.out.println("<= 0.5: " + counterLessOrEqual + " times");
		
		if (counterLessOrEqual > 0 && counterMore > 0){
			double ratio = (counterLessOrEqual < counterMore) ? (((double)counterLessOrEqual) / counterMore) : (((double)counterMore) / counterLessOrEqual);
			System.out.println("Ratio: " + ratio);
		}


	}
}
